"""Batch B: 010 Handling Events (12), 012 Using useState (24), 013 Why React Renders (18)."""
import os, json, sys, re, unicodedata
sys.stdout.reconfigure(encoding="utf-8")

BASE = r"D:\Personal\Downloads\react\.translate\inline"

def norm(s):
    s = unicodedata.normalize("NFKC", s)
    s = s.replace("\u00a0", " ").replace("\u2013", "-").replace("\u2014", "-")
    s = s.replace("\u2018", "'").replace("\u2019", "'").replace("\u201c", '"').replace("\u201d", '"')
    s = re.sub(r"\s+", " ", s).strip()
    return s

TRANS = {}

TRANS["010 - Handling Events - ui.dev"] = {
    "Let's start off with the most basic example, alerting <span class=\"sparkle_wrapper__cL2jQ\"><span class=\"sparkle_sparkle_wrapper__Izdcu\" style=\"top:35%;left:2%\"><svg class=\"sparkle_sparkle_svg__WdZ3Y\" fill=\"none\" height=\"19\" viewbox=\"0 0 68 68\" width=\"19\"><path d=\"M 48 5 L 51 27 L 74 30 L 51 33 L 48 56 L 44 33 L 23 30 L 44 27 Z\" fill=\"var(--yellow)\"></path></svg></span><span class=\"sparkle_sparkle_wrapper__Izdcu\" style=\"top:89%;left:5%\"><svg class=\"sparkle_sparkle_svg__WdZ3Y\" fill=\"none\" height=\"15\" viewbox=\"0 0 68 68\" width=\"15\"><path d=\"M 48 5 L 51 27 L 74 30 L 51 33 L 48 56 L 44 33 L 23 30 L 44 27 Z\" fill=\"var(--yellow)\"></path></svg></span><strong class=\"sparkle_child_wrapper__bem0y\">OUCH</strong></span> whenever a user clicks on a button.":
        "我们先从最基础的例子开始 —— 当用户点击按钮时弹出 <span class=\"sparkle_wrapper__cL2jQ\"><span class=\"sparkle_sparkle_wrapper__Izdcu\" style=\"top:35%;left:2%\"><svg class=\"sparkle_sparkle_svg__WdZ3Y\" fill=\"none\" height=\"19\" viewbox=\"0 0 68 68\" width=\"19\"><path d=\"M 48 5 L 51 27 L 74 30 L 51 33 L 48 56 L 44 33 L 23 30 L 44 27 Z\" fill=\"var(--yellow)\"></path></svg></span><span class=\"sparkle_sparkle_wrapper__Izdcu\" style=\"top:89%;left:5%\"><svg class=\"sparkle_sparkle_svg__WdZ3Y\" fill=\"none\" height=\"15\" viewbox=\"0 0 68 68\" width=\"15\"><path d=\"M 48 5 L 51 27 L 74 30 L 51 33 L 48 56 L 44 33 L 23 30 L 44 27 Z\" fill=\"var(--yellow)\"></path></svg></span><strong class=\"sparkle_child_wrapper__bem0y\">OUCH</strong></span>。",
    "Next, you'll notice that we're passing our event handler as a <em metastring=\"\">reference</em> to <code>onClick</code>, not as an <em metastring=\"\">invocation</em>. Note the difference between these two <code>onClick</code> props.":
        "其次，注意我们是把事件处理函数作为<em metastring=\"\">引用</em>传给 <code>onClick</code>，而不是作为<em metastring=\"\">调用</em>。留意这两种 <code>onClick</code> prop 的区别。",
    "If we pass <code>onClick</code> an <em metastring=\"\">invocation</em>, à la <code>handleClick()</code>, as soon as the JavaScript engine encounters the invocation, it will invoke the function and pass the return value to <code>onClick</code>. This is obviously not what we want.":
        "如果我们给 <code>onClick</code> 传的是<em metastring=\"\">调用</em>形式（比如 <code>handleClick()</code>），那 JavaScript 引擎一碰到这个调用就会立刻执行函数，并把返回值传给 <code>onClick</code>。显然这不是我们想要的。",
    "Instead, we want to pass <code>onClick</code> a <em metastring=\"\">reference</em> to the function, so that it can invoke the function when the event occurs.":
        "我们真正想做的是把函数的<em metastring=\"\">引用</em>传给 <code>onClick</code>，这样它才能在事件发生时自己去调用函数。",
    "Next, you'll notice that we created our event handler <em metastring=\"\">inside</em> the component, not outside of it. This is also a common pattern, but it may feel unintuitive at first. Can you think of why we do this?":
        "另一个细节是，我们把事件处理函数写在了 component <em metastring=\"\">内部</em>，而不是外部。这也是常见写法，但乍看可能不太直观。你能想到原因吗？",
    "We no longer have access to <code>message</code> via scope. Instead, we have to pass it as an argument to <code>handleClick</code>, which forces us to create <em metastring=\"\">another</em> function that we pass to <code>onClick</code>. This indirection is unnecessary and is a good indication that we should move <code>handleClick</code> back inside of our component so we can take advantage of lexical scoping.":
        "我们不再能通过作用域直接拿到 <code>message</code>，只能把它作为参数传给 <code>handleClick</code>，这就逼得我们必须再多写<em metastring=\"\">一个</em>函数再传给 <code>onClick</code>。这种多一层间接的写法完全没必要，也明确说明了我们应该把 <code>handleClick</code> 搬回 component 内部，好利用词法作用域。",
    "So at this point you know how to add a click handler to a <code>button</code> (which is <span class=\"font-black tracking-wider\" style=\"color:var(--blue)\">cool</span>), but let's look at a scenario that isn't straight out of a generic React tutorial.":
        "至此你已经知道如何给 <code>button</code> 加点击处理函数了（<span class=\"font-black tracking-wider\" style=\"color:var(--blue)\">不错</span>），下面来看一个不那么像通用 React 教程的场景。",
    "Now let's work on our event handler that we'll pass as an <button aria-controls=\"radix-:rau:\" aria-expanded=\"false\" aria-haspopup=\"dialog\" class=\"Popover_children__8p5Di\" data-state=\"closed\" type=\"button\"><span><code>onCopy</code></span> <svg class=\"fill-brand-purple dark:fill-brand-yellow w-2 h-2 b-2 mx-0.5 mb-4\" enable-background=\"new 0 0 455 455\" version=\"1.1\" viewbox=\"0 0 455 455\" x=\"0\" xml:space=\"preserve\" xmlns=\"http://www.w3.org/2000/svg\" y=\"0\"><path d=\"M347.49 227L454.5 165.212 394.508 61.288 287.5 123.077 287.5 0 167.5 0 167.5 123.077 60.492 61.288 0.499 165.212 107.51 227 0.5 288.788 60.492 392.712 167.5 330.923 167.5 455 287.5 455 287.5 330.923 394.508 392.712 454.501 288.788z\"></path></svg></button> prop to each of our three emojis.":
        "现在来写事件处理函数，我们要把它作为 <button aria-controls=\"radix-:rau:\" aria-expanded=\"false\" aria-haspopup=\"dialog\" class=\"Popover_children__8p5Di\" data-state=\"closed\" type=\"button\"><span><code>onCopy</code></span> <svg class=\"fill-brand-purple dark:fill-brand-yellow w-2 h-2 b-2 mx-0.5 mb-4\" enable-background=\"new 0 0 455 455\" version=\"1.1\" viewbox=\"0 0 455 455\" x=\"0\" xml:space=\"preserve\" xmlns=\"http://www.w3.org/2000/svg\" y=\"0\"><path d=\"M347.49 227L454.5 165.212 394.508 61.288 287.5 123.077 287.5 0 167.5 0 167.5 123.077 60.492 61.288 0.499 165.212 107.51 227 0.5 288.788 60.492 392.712 167.5 330.923 167.5 455 287.5 455 287.5 330.923 394.508 392.712 454.501 288.788z\"></path></svg></button> prop 传给这三个 emoji 中的每一个。",
    "This does bring up a new scenario though. We now need to know some specific information about the event that was triggered. Specifically, we need to know <em metastring=\"\">which</em> emoji was copied so we can see if it was the right one.":
        "不过这里出现了新的情况。我们现在需要知道所触发事件的一些具体信息 —— 具体来说，是<em metastring=\"\">哪一个</em> emoji 被复制了，这样才能判断是不是对的那个。",
    "<button aria-controls=\"radix-:rc7:\" aria-expanded=\"false\" aria-haspopup=\"dialog\" aria-label=\"onGotPointerCapture\" class=\"Popover_children__8p5Di\" data-state=\"closed\" style=\"text-decoration:none\" type=\"button\"><span><p class=\"text-[16px] font-bold py-1\">onGotPointerCapture<span class=\"font-bold pr-2\">, </span></p></span> </button>":
        "<button aria-controls=\"radix-:rc7:\" aria-expanded=\"false\" aria-haspopup=\"dialog\" aria-label=\"onGotPointerCapture\" class=\"Popover_children__8p5Di\" data-state=\"closed\" style=\"text-decoration:none\" type=\"button\"><span><p class=\"text-[16px] font-bold py-1\">onGotPointerCapture<span class=\"font-bold pr-2\">, </span></p></span> </button>",
    "<button aria-controls=\"radix-:rc8:\" aria-expanded=\"false\" aria-haspopup=\"dialog\" aria-label=\"onLostPointerCapture\" class=\"Popover_children__8p5Di\" data-state=\"closed\" style=\"text-decoration:none\" type=\"button\"><span><p class=\"text-[16px] font-bold py-1\">onLostPointerCapture<span class=\"font-bold pr-2\">, </span></p></span> </button>":
        "<button aria-controls=\"radix-:rc8:\" aria-expanded=\"false\" aria-haspopup=\"dialog\" aria-label=\"onLostPointerCapture\" class=\"Popover_children__8p5Di\" data-state=\"closed\" style=\"text-decoration:none\" type=\"button\"><span><p class=\"text-[16px] font-bold py-1\">onLostPointerCapture<span class=\"font-bold pr-2\">, </span></p></span> </button>",
    "<button aria-controls=\"radix-:rdf:\" aria-expanded=\"false\" aria-haspopup=\"dialog\" aria-label=\"onAnimationIteration\" class=\"Popover_children__8p5Di\" data-state=\"closed\" style=\"text-decoration:none\" type=\"button\"><span><p class=\"text-[16px] font-bold py-1\">onAnimationIteration</p></span> </button>":
        "<button aria-controls=\"radix-:rdf:\" aria-expanded=\"false\" aria-haspopup=\"dialog\" aria-label=\"onAnimationIteration\" class=\"Popover_children__8p5Di\" data-state=\"closed\" style=\"text-decoration:none\" type=\"button\"><span><p class=\"text-[16px] font-bold py-1\">onAnimationIteration</p></span> </button>",
}

TRANS["012 - Using useState - ui.dev"] = {
    "Though creating a simple <code>Counter</code> app is <span class=\"font-black tracking-wider\" style=\"color:var(--blue)\">cool</span> and gives us a gentle introduction to <code>useState</code>, it's not <em metastring=\"\">super</em> practical. Let's look at some other use cases that'll give us more insight into how we can leverage <code>useState</code> in more scenarios.":
        "写一个简单的 <code>Counter</code> 应用<span class=\"font-black tracking-wider\" style=\"color:var(--blue)\">挺酷</span>，也让我们轻松入门了 <code>useState</code>，但它其实不<em metastring=\"\">太</em>实用。下面看几个别的用例，让我们更清楚地了解如何在更多场景里用好 <code>useState</code>。",
    "It's important to note that when you pass a value to <code>useState</code>'s updater function, whatever value you pass will always <strong metastring=\"\">replace</strong> the current piece of state.":
        "要特别注意：当你把一个值传给 <code>useState</code> 的更新函数时，不管传什么，它都会<strong metastring=\"\">替换</strong>当前这块 state。",
    "Instead of replacing the object, you most likely want to <strong metastring=\"\">merge</strong> the new value with the existing state object. To do that, we can use JavaScript's spread operator to spread all of the existing key/value pairs onto a new object, then pass that new object to the updater function.":
        "你大概率想要的不是替换整个对象，而是把新值<strong metastring=\"\">合并</strong>到已有的 state 对象上。做法是用 JavaScript 的展开运算符把现有的所有键值对展开到一个新对象里，然后再把这个新对象传给更新函数。",
    "At this point our app is progressing <del metastring=\"\">slowly</del> nicely. Unfortunately, it still doesn't resemble much of a todo <em metastring=\"\">list</em>.":
        "到这里，我们的应用<del metastring=\"\">慢慢</del>进展得不错。可惜它看起来还不太像一个 todo <em metastring=\"\">列表</em>。",
    "What if instead of having each <code>Todo</code> component manage its own state, we <span class=\"font-bold relative m-px\" style=\"bottom:0px\">l</span><span class=\"font-bold relative m-px\" style=\"bottom:1px\">i</span><span class=\"font-bold relative m-px\" style=\"bottom:2px\">f</span><span class=\"font-bold relative m-px\" style=\"bottom:3px\">t</span> that state up to the parent <code>TodoList</code> component?":
        "假如我们不让每个 <code>Todo</code> component 自己管理 state，而是把 state <span class=\"font-bold relative m-px\" style=\"bottom:0px\">提</span><span class=\"font-bold relative m-px\" style=\"bottom:1px\">升</span><span class=\"font-bold relative m-px\" style=\"bottom:2px\">上</span><span class=\"font-bold relative m-px\" style=\"bottom:3px\">去</span>到父组件 <code>TodoList</code> 会怎么样？",
    "This would solve all of our problems. <code>TodoList</code> would <em metastring=\"\">own</em> (and manage) the state of each todo item and then we can pass data down to components that need it via props.":
        "这样就能解决我们所有的问题。<code>TodoList</code> 会<em metastring=\"\">拥有</em>（并管理）每一个 todo 项的 state，我们再通过 props 把数据传给需要的子组件。",
    "The only gotcha is how you update that state. Often times when lifting state up, you decouple <em metastring=\"\">where</em> the state lives from the event handlers that update that state.":
        "唯一要注意的是：你怎么更新这个 state。往上提升 state 时，state 所在的位置往往和更新 state 的事件处理函数解耦开了。",
    "So first, let's <span class=\"font-bold relative m-px\" style=\"bottom:0px\">l</span><span class=\"font-bold relative m-px\" style=\"bottom:1px\">i</span><span class=\"font-bold relative m-px\" style=\"bottom:2px\">f</span><span class=\"font-bold relative m-px\" style=\"bottom:3px\">t</span> our <span class=\"ch-section-link\" data-active=\"false\">todo state</span> up to a new <code>TodoList</code> component and then pass it down via a prop to the <span class=\"ch-section-link\" data-active=\"false\">Todo</span> component.":
        "首先，我们把 <span class=\"ch-section-link\" data-active=\"false\">todo state</span> <span class=\"font-bold relative m-px\" style=\"bottom:0px\">提</span><span class=\"font-bold relative m-px\" style=\"bottom:1px\">升</span><span class=\"font-bold relative m-px\" style=\"bottom:2px\">上</span><span class=\"font-bold relative m-px\" style=\"bottom:3px\">去</span>到一个新的 <code>TodoList</code> component 里，然后通过 prop 往下传给 <span class=\"ch-section-link\" data-active=\"false\">Todo</span> component。",
    "First, we'll remove the local <code>todo</code> state and accept it as a <span class=\"ch-section-link\" data-active=\"false\">prop</span> since it now lives inside of the parent <span class=\"ch-section-link\" data-active=\"false\"><code>TodoList</code></span> component.":
        "首先，我们删掉本地的 <code>todo</code> state，改为把它作为 <span class=\"ch-section-link\" data-active=\"false\">prop</span> 接收 —— 因为它现在放在父组件 <span class=\"ch-section-link\" data-active=\"false\"><code>TodoList</code></span> 里了。",
    "Next, we'll update our event handlers to use our new <code>handleUpdateTodo</code> prop that we also passed down from the parent <span class=\"ch-section-link\" data-active=\"false\"><code>TodoList</code></span> component.":
        "接下来，我们更新事件处理函数，让它们使用从父组件 <span class=\"ch-section-link\" data-active=\"false\"><code>TodoList</code></span> 往下传的新 prop <code>handleUpdateTodo</code>。",
    "Notice that <code>handleUpdateTodo</code> has an <span class=\"ch-section-link\" data-active=\"false\"><code>updatedTodo</code></span> parameter. This is how we get data from where the event handlers live, in a child component, back up to where the state lives, in the parent component.":
        "注意 <code>handleUpdateTodo</code> 有一个 <span class=\"ch-section-link\" data-active=\"false\"><code>updatedTodo</code></span> 参数。事件处理函数住在子组件里，state 住在父组件里 —— 正是通过这个参数，我们把数据从子组件回传给父组件。",
    "It doesn't matter <em metastring=\"\">where</em> <code>handleUpdateTodo</code> is called, it just matters that when it's called, it receives this <code>updatedTodo</code> argument.":
        "<code>handleUpdateTodo</code> 在<em metastring=\"\">哪里</em>被调用并不重要，重要的是它被调用时能收到 <code>updatedTodo</code> 这个参数。",
    "So now inside of the child <code>Todo</code> component, we need to make sure when we invoke <span class=\"ch-section-link\" data-active=\"false\">handleUpdateTodo</span>, we pass it the updated todo item.":
        "所以在子组件 <code>Todo</code> 里，调用 <span class=\"ch-section-link\" data-active=\"false\">handleUpdateTodo</span> 时必须把更新后的 todo 项传过去。",
    "At this point our app is in better shape than it was before, but it's still not a todo <strong metastring=\"\">list</strong>. Let's fix that.":
        "到这里，应用状态比之前好了，但它还不是一个 todo <strong metastring=\"\">列表</strong>。我们来把这个补上。",
    "We'll do the same thing here by updating the state in our <code>TodoList</code> component to be an <em metastring=\"\">array</em> of todo objects, rather than just a single todo object.":
        "这里同样做一次类似的改动：把 <code>TodoList</code> component 里的 state 改成一个 todo 对象的<em metastring=\"\">数组</em>，而不是单个 todo 对象。",
    "Similar to objects, whenever you want to update an array that's on state, you need to pass the updater function a <strong metastring=\"\">new</strong> array which will replace the current array.":
        "和对象一样，每当你要更新 state 里的数组时，都要传给更新函数一个<strong metastring=\"\">新的</strong>数组，用它来替换当前的数组。",
    "In this case, because <code>TodoList</code> is the component that owns our <span class=\"ch-section-link\" data-active=\"false\"><code>todos</code></span> state, we'll want to create our function for deleting todo items in the same component.":
        "在这里，因为 <code>TodoList</code> 就是拥有 <span class=\"ch-section-link\" data-active=\"false\"><code>todos</code></span> state 的组件，我们就把删除 todo 项的函数放在同一个组件里写。",
    "Let's call it <code>handleDeleteTodo</code> and have it take in the <span class=\"ch-section-link\" data-active=\"false\"><code>id</code></span> of the todo item to delete as its only argument.":
        "我们叫它 <code>handleDeleteTodo</code>，它的唯一参数是要删除的 todo 项的 <span class=\"ch-section-link\" data-active=\"false\"><code>id</code></span>。",
    "Though it may have been... <span class=\"font-black tracking-wider\" style=\"color:var(--red)\">painstaking</span>, hopefully at this point you feel confident with <em metastring=\"\">all</em> aspects of managing state in React – including updating objects/array state as well as <span class=\"font-bold relative m-px\" style=\"bottom:0px\">l</span><span class=\"font-bold relative m-px\" style=\"bottom:1px\">i</span><span class=\"font-bold relative m-px\" style=\"bottom:2px\">f</span><span class=\"font-bold relative m-px\" style=\"bottom:3px\">t</span><span class=\"font-bold relative m-px\" style=\"bottom:4px\">i</span><span class=\"font-bold relative m-px\" style=\"bottom:5px\">n</span><span class=\"font-bold relative m-px\" style=\"bottom:6px\">g</span> state up.":
        "虽然过程可能有点<span class=\"font-black tracking-wider\" style=\"color:var(--red)\">磨人</span>，但希望到这里你对在 React 中管理 state 的<em metastring=\"\">所有</em>方面都已经心中有数 —— 包括更新 object/array 类型的 state，以及<span class=\"font-bold relative m-px\" style=\"bottom:0px\">提</span><span class=\"font-bold relative m-px\" style=\"bottom:1px\">升</span><span class=\"font-bold relative m-px\" style=\"bottom:2px\">状</span><span class=\"font-bold relative m-px\" style=\"bottom:3px\">态</span><span class=\"font-bold relative m-px\" style=\"bottom:4px\">向</span><span class=\"font-bold relative m-px\" style=\"bottom:5px\">上</span><span class=\"font-bold relative m-px\" style=\"bottom:6px\">传</span>。",
    "Learning when and how to <span class=\"font-bold relative m-px\" style=\"bottom:0px\">l</span><span class=\"font-bold relative m-px\" style=\"bottom:1px\">i</span><span class=\"font-bold relative m-px\" style=\"bottom:2px\">f</span><span class=\"font-bold relative m-px\" style=\"bottom:3px\">t</span> state up is one of the most important aspects of state management in React.":
        "学会<span class=\"font-bold relative m-px\" style=\"bottom:0px\">什</span><span class=\"font-bold relative m-px\" style=\"bottom:1px\">么</span><span class=\"font-bold relative m-px\" style=\"bottom:2px\">时</span><span class=\"font-bold relative m-px\" style=\"bottom:3px\">候</span>以及如何把 state 提升上去，是 React state 管理中最重要的方面之一。",
    "Here's the rule of thumb – whenever you have state that multiple components depend on, you'll want to <span class=\"font-bold relative m-px\" style=\"bottom:0px\">l</span><span class=\"font-bold relative m-px\" style=\"bottom:1px\">i</span><span class=\"font-bold relative m-px\" style=\"bottom:2px\">f</span><span class=\"font-bold relative m-px\" style=\"bottom:3px\">t</span> that state up to the nearest parent component and then pass it <span class=\"font-bold relative m-px\" style=\"bottom:3px\">d</span><span class=\"font-bold relative m-px\" style=\"bottom:2px\">o</span><span class=\"font-bold relative m-px\" style=\"bottom:1px\">w</span><span class=\"font-bold relative m-px\" style=\"bottom:0px\">n</span> via props.":
        "经验法则是：当多个组件都依赖同一块 state 时，就把这块 state <span class=\"font-bold relative m-px\" style=\"bottom:0px\">提</span><span class=\"font-bold relative m-px\" style=\"bottom:1px\">升</span><span class=\"font-bold relative m-px\" style=\"bottom:2px\">到</span><span class=\"font-bold relative m-px\" style=\"bottom:3px\">上</span>级最近的共同父组件里，然后通过 props <span class=\"font-bold relative m-px\" style=\"bottom:3px\">往</span><span class=\"font-bold relative m-px\" style=\"bottom:2px\">下</span><span class=\"font-bold relative m-px\" style=\"bottom:1px\">传</span><span class=\"font-bold relative m-px\" style=\"bottom:0px\">递</span>。",
    "Whenever you're in a situation like this, what you'll want to do is create a <span class=\"ch-section-link\" data-active=\"false\">function</span> in the component where the state is located, and then pass that function down via <span class=\"ch-section-link\" data-active=\"false\">props</span>.":
        "每当遇到这种情况，你应该在 state 所在的组件里创建一个 <span class=\"ch-section-link\" data-active=\"false\">函数</span>，然后通过 <span class=\"ch-section-link\" data-active=\"false\">props</span> 把这个函数往下传。",
    "Then, you can pass data back up to the parent component by passing an <span class=\"ch-section-link\" data-active=\"false\">argument</span> to the function you passed down.":
        "然后，你就可以给那个你往下传的函数传一个 <span class=\"ch-section-link\" data-active=\"false\">参数</span>，把数据再送回父组件。",
    "The biggest thing to notice is the relationship between <span class=\"ch-section-link\" data-active=\"false\">handleUpdateTodo</span> in the parent component, and <span class=\"ch-section-link\" data-active=\"false\">handleCheckboxClick</span> and <span class=\"ch-section-link\" data-active=\"false\">handleEditTodo</span> in the child component.":
        "最值得注意的，是父组件里的 <span class=\"ch-section-link\" data-active=\"false\">handleUpdateTodo</span> 与子组件里的 <span class=\"ch-section-link\" data-active=\"false\">handleCheckboxClick</span>、<span class=\"ch-section-link\" data-active=\"false\">handleEditTodo</span> 之间的关系。",
}

TRANS["013 - Why React Renders - ui.dev"] = {
    "Though this equation gives us a simple mental model for how React works, there's one aspect of the equation that still, after all these years, seems to confuse people. Exactly <em metastring=\"\">when</em> and <em metastring=\"\">how</em> is <code>f</code> invoked? Or said differently, <span class=\"font-black tracking-wider\" style=\"color:var(--beige)\">exactly <em metastring=\"\">when</em> and <em metastring=\"\">how</em> does React update the view?</span>":
        "这个等式给了我们理解 React 工作方式的一个简单心智模型，但其中有一部分多年来仍让人困惑：<code>f</code> 到底<em metastring=\"\">什么时候</em>、<em metastring=\"\">怎么</em>被调用？换句话说，<span class=\"font-black tracking-wider\" style=\"color:var(--beige)\">React 到底<em metastring=\"\">什么时候</em>以及<em metastring=\"\">怎样</em>更新视图？</span>",
    "To better answer this, instead of starting with <em metastring=\"\">how</em> or <em metastring=\"\">when</em>, let's go back one step further and start from first principles. First, <em metastring=\"\">what</em> is <span class=\"sparkle_wrapper__cL2jQ\"><span class=\"sparkle_sparkle_wrapper__Izdcu\" style=\"top:45%;left:11%\"><svg class=\"sparkle_sparkle_svg__WdZ3Y\" fill=\"none\" height=\"19\" viewbox=\"0 0 68 68\" width=\"19\"><path d=\"M 48 5 L 51 27 L 74 30 L 51 33 L 48 56 L 44 33 L 23 30 L 44 27 Z\" fill=\"var(--yellow)\"></path></svg></span><span class=\"sparkle_sparkle_wrapper__Izdcu\" style=\"top:45%;left:1%\"><svg class=\"sparkle_sparkle_svg__WdZ3Y\" fill=\"none\" height=\"12\" viewbox=\"0 0 68 68\" width=\"12\"><path d=\"M 48 5 L 51 27 L 74 30 L 51 33 L 48 56 L 44 33 L 23 30 L 44 27 Z\" fill=\"var(--yellow)\"></path></svg></span><strong class=\"sparkle_child_wrapper__bem0y\">rendering</strong></span>?":
        "为了更好地回答这个问题，我们不从<em metastring=\"\">怎么</em>或<em metastring=\"\">什么时候</em>入手，而是再退一步，从第一性原理讲起。首先，<em metastring=\"\">什么</em>是<span class=\"sparkle_wrapper__cL2jQ\"><span class=\"sparkle_sparkle_wrapper__Izdcu\" style=\"top:45%;left:11%\"><svg class=\"sparkle_sparkle_svg__WdZ3Y\" fill=\"none\" height=\"19\" viewbox=\"0 0 68 68\" width=\"19\"><path d=\"M 48 5 L 51 27 L 74 30 L 51 33 L 48 56 L 44 33 L 23 30 L 44 27 Z\" fill=\"var(--yellow)\"></path></svg></span><span class=\"sparkle_sparkle_wrapper__Izdcu\" style=\"top:45%;left:1%\"><svg class=\"sparkle_sparkle_svg__WdZ3Y\" fill=\"none\" height=\"12\" viewbox=\"0 0 68 68\" width=\"12\"><path d=\"M 48 5 L 51 27 L 74 30 L 51 33 L 48 56 L 44 33 L 23 30 L 44 27 Z\" fill=\"var(--yellow)\"></path></svg></span><strong class=\"sparkle_child_wrapper__bem0y\">渲染</strong></span>？",
    "That naturally leads us to our next question, <em metastring=\"\">when</em> exactly does React re-render a component?":
        "这自然引出了下一个问题：React 到底<em metastring=\"\">什么时候</em>会重新渲染一个 component？",
    "With that, we now have our final <button aria-controls=\"radix-:rij:\" aria-expanded=\"false\" aria-haspopup=\"dialog\" class=\"Popover_children__8p5Di\" data-state=\"closed\" type=\"button\"><span>interrogative</span> <svg class=\"fill-brand-purple dark:fill-brand-yellow w-2 h-2 b-2 mx-0.5 mb-4\" enable-background=\"new 0 0 455 455\" version=\"1.1\" viewbox=\"0 0 455 455\" x=\"0\" xml:space=\"preserve\" xmlns=\"http://www.w3.org/2000/svg\" y=\"0\"><path d=\"M347.49 227L454.5 165.212 394.508 61.288 287.5 123.077 287.5 0 167.5 0 167.5 123.077 60.492 61.288 0.499 165.212 107.51 227 0.5 288.788 60.492 392.712 167.5 330.923 167.5 455 287.5 455 287.5 330.923 394.508 392.712 454.501 288.788z\"></path></svg></button>, <em metastring=\"\">how</em> does React actually know when the state of a component has changed? At this point it's fairly trivial and, once again, it has to do with our snapshot.":
        "由此，我们终于来到最后一个<button aria-controls=\"radix-:rij:\" aria-expanded=\"false\" aria-haspopup=\"dialog\" class=\"Popover_children__8p5Di\" data-state=\"closed\" type=\"button\"><span>疑问词</span> <svg class=\"fill-brand-purple dark:fill-brand-yellow w-2 h-2 b-2 mx-0.5 mb-4\" enable-background=\"new 0 0 455 455\" version=\"1.1\" viewbox=\"0 0 455 455\" x=\"0\" xml:space=\"preserve\" xmlns=\"http://www.w3.org/2000/svg\" y=\"0\"><path d=\"M347.49 227L454.5 165.212 394.508 61.288 287.5 123.077 287.5 0 167.5 0 167.5 123.077 60.492 61.288 0.499 165.212 107.51 227 0.5 288.788 60.492 392.712 167.5 330.923 167.5 455 287.5 455 287.5 330.923 394.508 392.712 454.501 288.788z\"></path></svg></button>：React 到底<em metastring=\"\">怎样</em>知道 component 的 state 变了？到这里这个问题已经相当简单，它又一次和我们前面说的 snapshot 有关。",
    "From there, if the event handler contains an invocation of <code>useState</code>'s updater function <strong metastring=\"\">and</strong> React sees that the new state is different than the state in the snapshot, React will trigger a re-render of the component – creating a new snapshot and updating the view.":
        "接下来，如果事件处理函数里包含对 <code>useState</code> 更新函数的调用，<strong metastring=\"\">并且</strong> React 发现新 state 和 snapshot 里的 state 不同，React 就会触发该 component 的重新渲染 —— 生成一个新的 snapshot，并更新视图。",
    "Again, React will only re-render if the event handler contains an invocation of <code>useState</code>'s updater function (✅) <strong metastring=\"\">and</strong> React sees that the new state is different than the state in the snapshot (❌).":
        "再强调一次：React 只有在事件处理函数里调用了 <code>useState</code> 的更新函数（✅），<strong metastring=\"\">且</strong> React 发现新 state 和 snapshot 里的 state 不同（❌）时，才会重新渲染。",
    "Instead, React will only re-render after it's taken into account every updater function inside of the event handler and it's sure what the final state is. So in our example, React will only re-render <strong metastring=\"\">once</strong> per click.":
        "React 只会在把事件处理函数里的所有更新函数都处理完、确定最终的 state 之后，才触发一次重新渲染。所以在我们的例子里，每次点击 React 只会<strong metastring=\"\">渲染一次</strong>。",
    "Very welcoming. Notice anything peculiar about how our app works, though? Before you play with it, try to guess <em metastring=\"\">when</em> our nested <code>Wave</code> component will re-render.":
        "挺热情的一个例子。不过你有没有注意到它有个地方挺怪？先别急着玩，试着猜一下：嵌套在里面的 <code>Wave</code> component 会在<em metastring=\"\">什么时候</em>重新渲染？",
    "Your intuition is probably thinking <strong metastring=\"\">never</strong>. After all, if React truly only re-renders when it absolutely has to, why would <code>Wave</code> ever re-render since it doesn't accept any props and has no state?":
        "你的直觉多半是“<strong metastring=\"\">永远不会</strong>”。毕竟，如果 React 真的只在绝对必要时才重新渲染，<code>Wave</code> 既没有 props 也没有 state，凭什么会重新渲染？",
    "Notice that <code>Wave</code> re-renders whenever we click the <code>button</code> (changing the <code>index</code> state inside of <code>Greeting</code>). This may not be intuitive, but it demonstrates an important aspect of React. Whenever state changes, React will re-render the component that owns that state <strong metastring=\"\">and</strong> all of its child components – regardless of whether or not those child components accept any props.":
        "注意，每次我们点击 <code>button</code>（改变 <code>Greeting</code> 内部的 <code>index</code> state）时，<code>Wave</code> 都会重新渲染。这可能不太直观，但它说明了 React 的一条重要规则：每当 state 变化时，React 会重新渲染拥有这块 state 的组件，<strong metastring=\"\">以及</strong>它的所有子组件 —— 无论那些子组件是否接收 props。",
    "Second, the assumption that React should only re-render child components if their props change works in a world where React components are <em metastring=\"\">always</em> pure functions and props are the only thing these components need to render. The problem, as anyone who has built a real world React app knows, is that isn't <em metastring=\"\">always</em> the case.":
        "第二，“只有 props 变化时才重新渲染子组件”这个假设，只有在组件<em metastring=\"\">始终</em>是纯函数、且 props 是组件渲染所需的唯一输入时才成立。而任何写过真实 React 项目的人都知道，<em metastring=\"\">并非</em>总是这样。",
    "Third, if you do have an expensive component and you want that component to opt out of this default behavior and <em metastring=\"\">only</em> re-render when its props change, you can use React's <code>React.memo</code> higher-order component.":
        "第三，如果你确实有个开销很大的组件，并且希望它退出这种默认行为、<em metastring=\"\">仅</em>在 props 变化时才重新渲染，可以使用 React 的高阶组件 <code>React.memo</code>。",
    "That's an exaggeration, but it does change things just a <em metastring=\"\">little</em> bit.":
        "虽然说得夸张了点，但它确实<em metastring=\"\">稍微</em>改变了一些事情。",
    "All our examples until this point have had strict mode <strong metastring=\"\">disabled</strong>, for obvious reasons. But so you can see it in action, here's our <code>Wave</code> example now in <code>StrictMode</code>.":
        "到目前为止，我们所有的例子都<strong metastring=\"\">关闭</strong>了严格模式，原因显而易见。不过为了让你看看效果，下面是放进 <code>StrictMode</code> 里的 <code>Wave</code> 例子。",
    "Notice that every time we click the button, our app renders <strong metastring=\"\">twice</strong>.":
        "注意，每次我们点击按钮，应用都会渲染<strong metastring=\"\">两次</strong>。",
    "Your intuition might be that React will re-render for every <span class=\"highlight-trigger font-medium underline decoration-brand-blue !cursor-help\" style=\"display:inline-block;white-space:nowrap\">updater</span> function it encounters, so 3 times in our example.":
        "你的直觉可能是：React 会为它遇到的每一个 <span class=\"highlight-trigger font-medium underline decoration-brand-blue !cursor-help\" style=\"display:inline-block;white-space:nowrap\">updater</span> 函数都重新渲染一次 —— 所以这个例子里会渲染 3 次。",
    "Now it's uncommon, but there is a way to tell React to use the value of the previous invocation of the updater function instead of replacing it. To do that, you pass the updater function a function itself that will take in the <span class=\"highlight-trigger font-medium underline decoration-brand-blue !cursor-help\" style=\"display:inline-block;white-space:nowrap\">value</span> from the most recent invocation as its <span class=\"highlight-trigger font-medium underline decoration-brand-blue !cursor-help\" style=\"display:inline-block;white-space:nowrap\">argument</span>.":
        "虽然不常见，但确实有办法让 React 使用上一次更新函数调用的值，而不是直接替换掉。做法是：给 updater 函数传一个函数，这个函数会把最近一次调用的 <span class=\"highlight-trigger font-medium underline decoration-brand-blue !cursor-help\" style=\"display:inline-block;white-space:nowrap\">值</span>作为它的 <span class=\"highlight-trigger font-medium underline decoration-brand-blue !cursor-help\" style=\"display:inline-block;white-space:nowrap\">参数</span>。",
    "Are you having <button aria-controls=\"radix-:ril:\" aria-expanded=\"false\" aria-haspopup=\"dialog\" class=\"Popover_children__8p5Di\" data-state=\"closed\" type=\"button\"><span>fun</span> <svg class=\"fill-brand-purple dark:fill-brand-yellow w-2 h-2 b-2 mx-0.5 mb-4\" enable-background=\"new 0 0 455 455\" version=\"1.1\" viewbox=\"0 0 455 455\" x=\"0\" xml:space=\"preserve\" xmlns=\"http://www.w3.org/2000/svg\" y=\"0\"><path d=\"M347.49 227L454.5 165.212 394.508 61.288 287.5 123.077 287.5 0 167.5 0 167.5 123.077 60.492 61.288 0.499 165.212 107.51 227 0.5 288.788 60.492 392.712 167.5 330.923 167.5 455 287.5 455 287.5 330.923 394.508 392.712 454.501 288.788z\"></path></svg></button> yet? Let's look at another example.":
        "<button aria-controls=\"radix-:ril:\" aria-expanded=\"false\" aria-haspopup=\"dialog\" class=\"Popover_children__8p5Di\" data-state=\"closed\" type=\"button\"><span>玩得还开心吗</span> <svg class=\"fill-brand-purple dark:fill-brand-yellow w-2 h-2 b-2 mx-0.5 mb-4\" enable-background=\"new 0 0 455 455\" version=\"1.1\" viewbox=\"0 0 455 455\" x=\"0\" xml:space=\"preserve\" xmlns=\"http://www.w3.org/2000/svg\" y=\"0\"><path d=\"M347.49 227L454.5 165.212 394.508 61.288 287.5 123.077 287.5 0 167.5 0 167.5 123.077 60.492 61.288 0.499 165.212 107.51 227 0.5 288.788 60.492 392.712 167.5 330.923 167.5 455 287.5 455 287.5 330.923 394.508 392.712 454.501 288.788z\"></path></svg></button>？我们再看一个例子。",
}

def fill(stem, mapping):
    path = os.path.join(BASE, stem + ".json")
    with open(path, "r", encoding="utf-8") as f:
        d = json.load(f)
    norm_map = {norm(k): v for k, v in mapping.items()}
    filled = 0
    for k in list(d.keys()):
        if d[k]: continue
        nk = norm(k)
        if nk in norm_map:
            d[k] = norm_map[nk]
            filled += 1
    with open(path, "w", encoding="utf-8") as f:
        json.dump(d, f, ensure_ascii=False, indent=2)
    missing = sum(1 for v in d.values() if not v)
    print(f"  {stem[:3]}  filled={filled}  still-missing={missing}")

for stem, mapping in TRANS.items():
    fill(stem, mapping)